version: '3.9'
services:
  mysql:
    image: mysql
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Jakarta
      # - MYSQL_SQL_MODE=""
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/custom.cnf:/etc/mysql/conf.d/my-custom.cnf
    ports:
      - 3307:3306
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    # command: --server-id=1 --log_bin
  gofiber-repository-pattern:
    image: 'ghcr.io/prioarief/gofiber-repository-pattern'
    restart: 'always'
    container_name: 'gofiber-repository-pattern'
    environment:
      - port=3000
      - APP_NAME=gofiber-repository-pattern
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=golang_restapi
      - DB_PORT=3307
    ports:
      - '3000:3000'
